//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3CodeDemo.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_Detail = new HashSet<Bill_Detail>();
        }
    
        public int ID_Bill { get; set; }
        public Nullable<int> ID_Account { get; set; }
        public Nullable<int> ID_Table { get; set; }
        public Nullable<bool> Pay_Status { get; set; }
        public Nullable<System.DateTime> Order_Day { get; set; }
        public Nullable<System.TimeSpan> Order_Time { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<int> New_ID_Table { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Table Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Detail> Bill_Detail { get; set; }
    }
}
