//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3CodeDemo.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public int ID_Item { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> Flag { get; set; }

        public static implicit operator InventoryItem(InventoryItem v)
        {
            throw new NotImplementedException();
        }
    }
}
