//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3CodeDemo.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int IdShift { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public Nullable<int> ShiftNumber { get; set; }
        public Nullable<int> Date { get; set; }
        public Nullable<bool> FlagAssigned { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
